Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -34,7 +34,29 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install -r tests/requirements.txt
-    - name: Test with pytest
+    - name: Test with pytest (Linux)
+      if: runner.os == 'Linux'
+      run: |
+        coverage run -m pytest \
+          -c ./tests/pytest.ini \
+          -W ignore::pytest.PytestCollectionWarning \
+          --md-report --md-report-output=report.md --md-report-color=never \
+          tests || pytest_exit_code=$?
+        echo "## :clipboard: Test Results" >> $GITHUB_STEP_SUMMARY
+        cat report.md >> $GITHUB_STEP_SUMMARY
+        echo "## :bar_chart: Code coverage" >> $GITHUB_STEP_SUMMARY
+        coverage report --format markdown >> $GITHUB_STEP_SUMMARY
+        if [[ "$(coverage report --format total)" -lt 80 ]]
+        then
+          echo "::error::Code coverage is less than 80%" && exit_code=1
+        fi
+        if [[ $pytest_exit_code -gt 0 ]]
+        then
+          echo "::error::Unit tests failed" && exit_code=1
+        fi
+        exit $exit_code
+    - name: Test with pytest (Windows)
+      if: runner.os == 'Windows'
       run: |
         coverage run -m pytest \
           -c ./tests/pytest.ini \
